### ISSUE TITLE
Day 3 notes and resources

### ISSUE THREAD

**Issue by manpreetsngh293** [vivekanandpv/angular-notes#1]
Requesting the notes for day 3 angular training(Fidelity) and learning materials.

**Comment by vivekanandpv** [comment]
Will do it in a day or two

**Comment by vivekanandpv** [comment]
Done

**Comment by manpreetsngh293** [comment]
@vivekanandpv These are extremely helpful. Thanks a lot for taking time to prepare these.

**Comment by vivekanandpv** [comment]
My pleasure Manpreet.
